services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/JuusoVault/main/Jellyfin:/movies
      - /mnt/JuusoVault/main/Jellyfin books:/books
      - /mnt/JuusoVault/main/Jellyfin music:/music
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.100
    extra_hosts:
      - "host.docker.internal:host-gateway"
